export const categoryLinks: string[] = [
  'All',
  'Music',
  'Gaming',
  'Youth music',
  'Mixes',
  'CrossFire',
  'News',
  'Lofi',
  'Marital Arts Movies',
  'React Js',
  'Typescript',
  'Redux Toolkit',
  'YouTube API',
  'FirebaseV9',
  'Motorcycles',
  'Recently uploaded',
  'Watched',
  'New to you',
  'Humans',
  'Python',
]
